---
#Here you should add, edit or remove sounds for each event.
#Removing events will not make any sense.If you want to disable sounds for any event, Set its value to 0

JoinEvent: 2
QuitEvent: 2
ChatEvent: 10
DeathEvent: 17
