#Don't make any changes in configVersion
configVersion: 2

#Allow EventSounds to detect other plugins event.
enableExternalEvents: false

#Here you can edit the sound ID and who can hear it for each event.
#Sounds IDs can be found in soundsIDs.txt .
#At the hearby : 1 = player who called the event. 2 = Everyone except the player. 3 = Everyone in the world.

LoginEvent:
    sound: 0
    hearby: 3
JoinEvent:
    sound: 2
    hearby: 3
QuitEvent:
    sound: 2
    hearby: 3
ChatEvent:
    sound: 10
    hearby: 2
DeathEvent:
    sound: 17
    hearby: 3
GamemodeEvent:
    sound: 3
    hearby: 2
TransferEvent:
    sound: 19
    hearby: 2
