---
#Here you should add, edit or remove sounds for each event.
#Adding or removing events doesn't make any sense.If you want to disable sounds for any event, Set its value to 0

LoginEvent: 11
JoinEvent: 2
QuitEvent: 2
ChatEvent: 10
DeathEvent: 17
GamemodeEvent: 3
TransferEvent: 19
